Controllers/ContentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using CmsLocalization.AutoMapperMapping;
using CmsLocalization.DB;
using CmsLocalization.Infastructure;
using CmsLocalization.Models;
using Microsoft.AspNetCore.Mvc;


namespace CmsLocalization.Controllers
{
    public class ContentController : ControllerBase
    {
        private readonly IMapper _mapper;

        private readonly IContentRepository _contentRepository;
        private readonly IContentMappingRepository _contentMappingRepository;
        private readonly ILanguageRepository _languageRepository;

        public ContentController(IContentRepository contentRepository, IContentMappingRepository contentMappingRepository,
            ILanguageRepository languageRepository, IMapper mapper)
        {
            _contentRepository = contentRepository;
            _contentMappingRepository = contentMappingRepository;
            _languageRepository = languageRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var contents = _contentRepository.GetAll();
            return View(contents);
        }

        public IActionResult Create()
        {
            var model = new ContentModel();
            model.Languages = _languageRepository.GetAll().ToList();

            //get mapping proporties
            AddLocales(_languageRepository, model.Locales);
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(ContentModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var content = model.ToEntity(_mapper);
                    content.CreatedBy = "Berkay";
                    _contentRepository.Insert(content); //create content and mappings
                    _contentRepository.Save();

                    TempData["Message"] = "The new content has been added successfully.";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
            }
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var content = _contentRepository.GetById(id);
            if (content == null)
                return RedirectToAction("Index");

            try
            {
                var mappingModel = new List<ContentMappingModel>();
                var contentModel = content.ToModel(_mapper);
                AddLocales(_languageRepository, mappingModel, (locale, languageId) =>
                {
                    foreach (var item in contentModel.Locales.Where(l => l.LanguageId == languageId))
                    {
                        locale.Title = item.Title;
                        locale.SubTitle = item.SubTitle;
                        locale.Description = item.Description;
                    }
                });
                contentModel.Languages = _languageRepository.GetAll().ToList();
                return View(contentModel);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.ToString();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(ContentModel model)
        {
            var content = _contentRepository.GetById(model.Id);
            if (content == null)
                return RedirectToAction("Index");

            if (ModelState.IsValid)
            {
                try
                {
                    content = model.ToEntity(content, _mapper);
                    _contentRepository.Update(content); //update content and mappings

                    TempData["Message"] = "The content has been updated successfully.";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
            }
            model.Languages = _languageRepository.GetAll().ToList();
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            var content = _contentRepository.GetById(id);
            if (content == null)
                return RedirectToAction("Index");

            try
            {
                _contentRepository.Delete(content);
                _contentRepository.Save();
                TempData["Message"] = "The content has been deleted successfully.";
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.ToString();
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using CmsLocalization.AutoMapperMapping;
using CmsLocalization.Infastructure;
using CmsLocalization.Models;
using Microsoft.AspNetCore.Mvc;


namespace CmsLocalization.Controllers
{
    public class LanguageController : Controller
    {
        private readonly IMapper _mapper;
        private readonly ILanguageRepository _languageRepository;

        public LanguageController(ILanguageRepository languageRepository, IMapper mapper)
        {
            _languageRepository = languageRepository;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var languages = _languageRepository.GetAll();
            return View(languages);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(LanguageModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var language = model.ToEntity(_mapper);
                    language.CreatedBy = "Berkay";
                    _languageRepository.Insert(language);
                    _languageRepository.Save();
                    TempData["Message"] = "The new language has been added successfully.";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
            }
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var language = _languageRepository.GetById(id);
            if (language == null)
                return RedirectToAction("Index");

            try
            {
                var languageModel = language.ToModel(_mapper);
                return View(languageModel);
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.ToString();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Edit(LanguageModel model)
        {
            var language = _languageRepository.GetById(model.Id);
            if (language == null)
                return RedirectToAction("Index");

            if (ModelState.IsValid)
            {
                try
                {
                    language = model.ToEntity(language, _mapper);
                    _languageRepository.Update(language);
                    TempData["Message"] = "The language has been updated successfully.";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ViewBag.Message = ex.ToString();
                }
            }
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            var language = _languageRepository.GetById(id);
            if (language == null)
                return RedirectToAction("Index");

            try
            {
                _languageRepository.Delete(language);
                _languageRepository.Save();
                TempData["Message"] = "The language has been deleted successfully.";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.ToString();
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewData["Title"] - CMS Localization</title>
    <link rel="stylesheet" href="~/css/style.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="~/js/jquery-1.12.4.min.js"></script>
    <script src="~/js/materialize.min.js"></script>
    <script src="~/js/custom.js"></script>
</head>

<body id="dashboard">
    <header id="Header">
        <div class="col xs-1-2 sm-1-2 md-1-2 lg-1-2">
            <div class="row">
                <div class="header-sign">
                    <div class="menu-opener" data-class="open" onclick="toggleElement(this)">
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                    <div class="site-logo">
                        <img src="~/img/net-core.png" alt="">

                    </div>
                </div>
            </div>
        </div>
        <div class="col xs-1-2 sm-1-2 md-1-2 lg-1-2 right-align">
            <div class="row">

                <div class="user-menu">
                    <div class="avatar"><span class="user-name">BE</span></div>
                    <div id='user-menu'>
                        <ul>
                            <li><a href="#">Logout</a></li>
                            <li><a href="#!">Settings</a></li>
                        </ul>
                    </div>                   
                </div>
            </div>
        </div>
    </header>
    <aside id="Side-bar">
        <div class="side-nav">
            <ul class="site-navigation">
                 <li><a asp-controller="Home" asp-action="Index" class="btn-flat waves-effect waves-light"><i class="material-icons">home</i><span>Home</span></a></li> 
                <li><a asp-controller="Content" asp-action="Index" class="btn-flat waves-effect waves-light"><i class="material-icons">content_copy</i><span>Contents</span></a></li> 
                <li><a asp-controller="Language" asp-action="Index" class="btn-flat waves-effect waves-light"><i class="material-icons">settings</i><span>Language</span></a></li>
            </ul>
        </div>
        <div class="user-menu">
            <div class="user"></div>
        </div>
    </aside>
    <main id="Wrapper">
        <div class="content">
            @RenderBody()
        </div>
    </main>
</body>
</html>